# NumPy Introduction

In [1]:
#Import libraries
import numpy as np

In [2]:
my_list = [1, 2, 3]

## Arrays

In [4]:
# create a numpy array
x = np.array(my_list)


In [5]:
type(x)

numpy.ndarray

In [6]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
list(range(0, 5))

[0, 1, 2, 3, 4]

In [ ]:
# arange - array range
np.arange(0, 5)

array([0, 1, 2, 3, 4])

### Array of zeros
* all items are of the same type
* The size of the array is set when we create the array

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Evenly spaced numbers over a specified interval - linearly spaced
np.linspace(0, 10, 3) # three evenly spaced numbers between 0 and 10

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0, 10, 30) # all consecutive numbers have even spacing between 0 and 10

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

In [17]:
np.linspace(0, 10, 51) # all consecutive numbers have even spacing between 0 and 10

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

### Identity matrix

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random numbers

In [20]:
np.random.rand(1) # random number between 0 and 1 uniform distribution. Meaning all numbers are equally likely ofbeing chosen

array([0.8109742])

In [21]:
np.random.rand(4, 5)

array([[0.7229956 , 0.84973933, 0.51400051, 0.10383779, 0.15327694],
       [0.52851569, 0.10303375, 0.14184574, 0.83313178, 0.56749351],
       [0.47156768, 0.34982333, 0.15205601, 0.42605784, 0.87100371],
       [0.79294742, 0.4742739 , 0.24540474, 0.62661173, 0.06434663]])

In [22]:
# generate rnumbers from a standard normal distribution (mean 0, variance 1)
np.random.randn(5) # 5 random numbers randomly chosen from standard normal distribution

array([-0.22954421, -0.28972468,  0.59742456,  0.75384067,  1.98337262])

In [23]:
np.random.randn(5, 4)

array([[-0.68906137,  0.59985473,  0.90129162, -0.49790879],
       [-0.75262829, -0.72676973,  0.29609236,  0.96267055],
       [-0.3503043 , -0.34073605,  0.25417328, -1.09372477],
       [-0.07570282, -0.41149015,  1.32144574,  1.67197418],
       [ 0.8559617 ,  0.40073941,  1.12104097, -0.34312013]])

In [24]:
# random integer from low (inclusive) to high (exclusive)
np.random.randint(1, 100)

78

In [25]:
np.random.randint(1, 100, 10)

array([59, 90, 48, 90, 35, 24, 20, 60, 66, 46])

In [26]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranarr

array([23, 44,  4,  3, 18,  8, 38, 17, 11, 10])

### Reshaping an array

In [29]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
arr.shape

(25,)

In [31]:
arr.reshape(5, 5).shape

(5, 5)

In [34]:
arr.reshape(25, 1).shape

(25, 1)

In [35]:
arr.dtype

dtype('int64')

In [36]:
ranarr

array([23, 44,  4,  3, 18,  8, 38, 17, 11, 10])

In [41]:
# grab the max value from ranarr
ranarr.max()

np.int64(44)

In [42]:
# grab the min value from ranarr
ranarr.min()   

np.int64(3)

In [44]:
# index location of max in ranarr
ranarr.argmax()

np.int64(1)

In [46]:
# index of hte min value in ranarr
ranarr.argmin()


np.int64(3)